env:
  global:
    - CXX=g++-4.8

addons:
  rethinkdb: '2.3'

# Do not insert any code under here without making sures it's in publishingtest first
language: node_js

plugins:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

node_js:
  - "6"
  - "4"

script:
  - npm run coverage

after_script:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
