environment:
  RETHINKDB_HOST: 54.93.147.100

# Do not insert any code under here without making sures it's in publishingtest first
os:
  - Visual Studio 2015

platform:
  - x64

install:
  - ps: Install-Product node 4.4.5
  - npm install

test_script:
  - npm test

build: off